### ISSUE TITLE
Stuck in Boot | Raspberry Pi 4B

### ISSUE THREAD

**Issue by Xenox003** [nooploop/piejam_os#1]
Hi, i just tried to install the piejam OS image onto my PI because i wanted to try out the system.
After grabbing the IMG file for the Pi 4B from the releases section and putting it into Raspberry PI imager i flashed the OS onto an 32 GB SD card and inserted it into my PI.

After powering it on i saw it beeing stuck in boot showing the PieJam booticon, since the system basically does not give me any detailed information about the boot i cannot give you any logs or whatever else. Its been like that for about 15 minutes now.

What could possible reasons for this be? I got my audio interface, my official RPI 7 inch screen and my power cable connected, thats all.

Thanks!

**Comment by nooploop** [comment]
On first boot it creates an additional data partition for recordings. 32GB is very big so it might take a while on first boot. So wait a bit more. With a smaller card (2GB or 4GB) it should boot faster on first boot.
After first boot, no matter with which card, it should boot in a few seconds.

**Comment by Xenox003** [comment]
Update: Its been about 2 hours now and still only the boot icon, my PI's CPU has got some decent constant temperature so it seems it does something.

Not sure if it didnt run into some random infinite loop, doesnt seem normal for creating partitions and moving some data around

**Comment by nooploop** [comment]
2 hours is not normal. For my 16gb card it took 5 minutes on first boot. Do you have an alternative sd card for testing, a smaller one?

Try to restart, maybe without the audio interface first.

Maybe the image was not flashed properly. There should be 3 partitions after flashing.

I'll try tomorrow with my pi4b. And see if i run into any problems.

**Comment by Xenox003** [comment]
I only have another 32 GB Card from my phone atm, i will still try it cause the card is way faster that the one i used, maybe that can also be an issue not sure.

**Comment by nooploop** [comment]
What you can also try is to mount the root partition. There delete the file `etc/init.d/S99piejamfs`
This should avoid the formatting on the first boot and boot directly into the app.

**Comment by Xenox003** [comment]
I also just checked the SD Card i had inside my PI first, after i took it out it had 2 partitions, Boot and a primary one, i flashed it for testing and it had 3 partitions then.

I will try deleting the file in init.d once i get dual boot on my laptop running again so i can read the linux filesystem.

**Comment by Xenox003** [comment]
The second SD Card also did not seem to boot properly

**Comment by Xenox003** [comment]
Just tried removing the S99piejamfs file, does not seem to fix the problem
I guess the partitioning works fine because when i checked the card that has been in first it was partitioned like the script is supposed to do.
I may run some more test tomorrow

**Comment by nooploop** [comment]
Hi,
i just downloaded the image and tried it out on my rpi4b (2gb) and it worked. So i'm very puzzled what issue you have. Nevertheless we can try something out. On the boot partition open the `cmdline.txt` file and:

- remove `quiet` keyword
- remove `loglevel=0` keyword
- change `console=tty2` to `console=tty1`
- after `console=tty1` add `logo.nologo`

This should disable the boot logo and show boot messages on the screen, maybe we then can see what's happening.

What version of rpi4b do you have?

**Comment by Xenox003** [comment]
Hi, ive got a Pi4B 2GB so the exactly same, ill try turning on the logging later today

**Comment by Xenox003** [comment]
Ok so if basically stops at the USB port detection first, after 116 seconds it tells me the crng init is done.

Nothing connected to the pi atm, fresh installation of piejam os only changed values in the cmdline.txt
![20220622_123552](https://user-images.githubusercontent.com/68594244/175009475-a9266980-1cec-4bcb-87a5-19a078660a4a.jpg)

Ill be waiting a few mins since i guess it does the partitioning now

**Comment by Xenox003** [comment]
According to this post: https://forums.raspberrypi.com/viewtopic.php?t=209093
It seems like the root FS is not mounting

my debian VM does not have problems mounting the rootfs so it cannot be the card i guess

**Comment by nooploop** [comment]
Yes root filesystem is not mounted.

So i did some experiments and tried different sd cards. I could reproduce it with a 16gb sd card on rpi4! The weird thing this same sd card works on rpi2. I had no problems with another 4gb sd card on rpi4.
I will try to figure out what's wrong with this sd card, maybe i forgot something when configuring the kernel. If i find a solution, i might need to release a fix for it.
In the meantime i can only suggest for you to get another sd card. Try some smaller ones first: 2gb or 4gb.

**Comment by nooploop** [comment]
So i think i found a solution after a bit of googling. Please add in `cmdline.txt` at the end of command line: `sdhci.debug_quirks2=4`

**Comment by Xenox003** [comment]
Hi, that thing finally booted and i got to test it for the first time.

I have to admin that i am literally amazed about how smooth that works with very low latency, i tested it with my Rode NT USB Mic and my headphones and i could literally use that to live monitor my voice, great job!
The MIDI CC integration is also very nice and works even better than in Voicemeeter.

Sadly you cannot use multiple audio interfaces but i guess i can setup a clone of this to feature multiple audio devices at the cost of a little latency, thats especially useful for people like me who aren't willing to buy huge Multi Channel audio interfaces and instead use multiple smaller ones like me with my 2 Behringer U-Control UCA222

**Comment by nooploop** [comment]
Cool!

Multiple interfaces might work somehow, i would need to think about it more. Also i can see that multiple USB devices can become a problem. RasPI's are notorious for their USB issues. And also, how should a configuration of multiple interfaces look like. There needs to be a nice way to do it without big compromises on user experience. Those are a quite a few problems there, which need to be solved.

**Comment by Xenox003** [comment]
So currently you are able to only select channels on different devices you add, what if you could directly set the device and the according channels in the device, example:
![image](https://user-images.githubusercontent.com/68594244/175110961-9ced8b03-5f4b-4164-a119-6cde4028cc7d.png)

For the Global Device settings id create a list of devices where you can view connected devices
The samplerate, period size and period count would need to be global because you cannot mix two interfaces with different samplerates

![image](https://user-images.githubusercontent.com/68594244/175111399-f7c3c34a-fd33-449e-87e7-59ba4345955b.png)


Maybe i can get something like this designed once i get my development VM running
