### ISSUE TITLE
ladspa update

### ISSUE THREAD

**Issue by adrianwalsh1990** [nooploop/piejam_os#2]
More of an FYI, the link for ladspa download wasn't working for me. I changed the link to 1.17 and it worked.

**Comment by adrianwalsh1990** [comment]
Sorry one other thing is the ladspa.hash file the md5 line I also had to change. 

Love the project, seems to do exactly what I'm looking for. Any plans to add Bluetooth as an output source?

**Comment by nooploop** [comment]
Thanks! Yes, you're right. Sadly the LADSPA project doesn't keep the old releases, so i need to rerelease my project every time they make an update. I will fix it, hopefully soon.
You mean Bluetooth support for headphones or microphones? No plans for Bluetooth so far. I need to make more research on this topic. Latency might be a problem for Bluetooth, but also depends on use-case scenarios.

**Comment by adrianwalsh1990** [comment]
Ah ya thats annoying. Ya Bluetooth headphones, but ya my use case is probably different to yours and latency doesn't matter for me. I think ill just get on of those aux Bluetooth adapters.
