### ISSUE TITLE
make[1]: *** No rule to make target `raspberrypi4_defconfig'.  Stop.

### ISSUE THREAD

**Issue by wewiley** [nooploop/piejam_os#3]
piejam_os % make raspberrypi4
make -C buildroot BR2_EXTERNAL="/private/tmp/piejam_os/br2_external" O="/private/tmp/piejam_os/br2_external/output/raspberrypi4" raspberrypi4_defconfig
make[1]: *** No rule to make target `raspberrypi4_defconfig'.  Stop.
make: *** [raspberrypi4-builddir] Error 2

***********************************
Unable to complete Makefile build process.  Same error on Pi 2,3,4
Running from Terminal on Mac OS 14.0

**Comment by nooploop** [comment]
You need to clone this project with submodules:

git clone --recurse-submodules https://github.com/nooploop/piejam_os.git

I probably should add it to the README.
