### ISSUE TITLE
Mouse and Keyboard Support

### ISSUE THREAD

**Issue by Matze5590** [nooploop/piejam_os#4]
Could you please add support for mouse and keyboard? otherwise we need to have the touchscreen...
Or am i doing something wrong?

**Comment by nooploop** [comment]
The initial use case was to use it with the raspi touchscreen and that's how i use it. What is your use case?

**Comment by Matze5590** [comment]
I would use it with a regular monitor to set things up. Then i would have it running without any screen, if thats possible

**Comment by nooploop** [comment]
I see. Yes this should be possible. Though i think i also disabled hdmi. Did you tried it already with a regular monitor?

**Comment by Matze5590** [comment]
It shows up on the monitor via hdmi, but i can not control it. Mouse and keyboard inputs dont work.

**Comment by nooploop** [comment]
Ok, i will add it. Though i can't give you a timeframe. Soon.

**Comment by Matze5590** [comment]
Wow, nice! Thanks a lot!

**Comment by nooploop** [comment]
Hi, i published a new release today: https://github.com/nooploop/piejam_os/releases/tag/v0.9.0
I added mouse support there, keyboard was already enabled before.
